services:
  bots-db:
    image: postgres:15.3-alpine3.18
    container_name: ir-bots-postgres
    command: postgres
    ports:
      - 30001:5432
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test-user -d test-db" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      ir-web-bots:
        aliases:
          - db

  bots-migrate:
    image: migrate/migrate
    container_name: ir-bots-migrate
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://test-user:test-pass@db:5432/test-db?sslmode=disable", "up" ]
    depends_on:
      bots-db:
        condition: service_healthy
    networks:
      - ir-web-bots

  bots-nats:
    image: nats:alpine
    container_name: ir-bots-nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ~/.docker/itsreg/nats/data:/data

networks:
  ir-web-bots:
    driver: bridge
