services:
  bots-http:
    container_name: ir-bots-http
    build:
      context: ../
      args:
        SERVICE: http
    ports:
      - 8400:${PORT:-8400}
    env_file:
      - ../.env
    depends_on:
      bots-db:
        condition: service_healthy
      bots-nats:
        condition: service_started
    networks:
      - ir-web-bots

  bots-telegram:
    container_name: ir-bots-telegram
    build:
      context: ../
      args:
        SERVICE: telegram
    env_file:
      - ../.env
    depends_on:
      bots-db:
        condition: service_healthy
      bots-nats:
        condition: service_started
    networks:
      - ir-web-bots

  bots-db:
    image: postgres:15.3-alpine3.18
    container_name: ir-bots-postgres
    command: postgres
    ports:
      - "54321:5432"
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      ir-web-bots:
        aliases:
          - db

  bots-migrate:
    image: migrate/migrate
    container_name: ir-bots-migrate
    networks:
      - ir-web-bots
    volumes:
      - ../migrations:/migrations
    env_file:
      - ../.env
    command: [ "-path", "/migrations", "-database", "$DATABASE_URI", "up" ]
    depends_on:
      bots-db:
        condition: service_healthy

  bots-nats:
    image: nats:alpine
    container_name: ir-bots-nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ~/.docker/itsreg/nats/data:/data
    networks:
      ir-web-bots:
        aliases:
          - nats

networks:
  ir-web-bots:
    driver: bridge
